### PR TITLE
Fix parsing response by its type

### LINKED ISSUE #199: Enable checkout response header check to convert into JSON object

### PR DESCRIPTION
**Pull request by LKay**
Closes #199

### CODE REVIEW

File: src/resources/TemporaryTokenAlias.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ export class TemporaryTokenAlias extends CRUDResource {
              id: string,
              data?: SendData<TemporaryTokenAliasQrOptions>,
              callback?: ResponseCallback<Blob>): Promise<Blob> {
-        return this.defineRoute(HTTPMethod.GET, `${this._routeBase}/:id`, [], true, false)
+        return this.defineRoute(HTTPMethod.GET, `${this._routeBase}/:id`, [], true)
             ({ media: "qr", ...data }, callback, ["storeId", "id"], storeId, id)
             .then((response: Response) => {
```
Comment (tom-myz) [inline src/resources/TemporaryTokenAlias.ts]: Thank you. I agree your idea of using content-type header is reasonable.
If `send` method returns blob, I think that these then blocks should be abolished, what about that?

Comment (LKay) [reply src/resources/TemporaryTokenAlias.ts]: You are absolutely right. Also methods for aliases have to be cleaned up a bit. I'll take care of this.
